version: '3.8'
services:
  web:
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf

  app:
    # image: php:7.4-fpm
    build: ./php
    depends_on:
      - mysql
    volumes:
      - '.:/var/www/html'

  mysql:
    image: mysql:8.0
    env_file:
      - .env
      # MYSQL_ROOT_PASSWORD
      # MYSQL_DATABASE
      # MYSQL_USER
      # MYSQL_PASSWORD

  chrome:
    image: selenium/standalone-chrome:85.0-chromedriver-85.0
    ports:
      - 4444:4444